### ISSUE TITLE
services -> wrong parameters passed to docker-compose command

### ISSUE THREAD

**Issue by tmontanaro** [FIWARE/tutorials.XACML-Access-Rules#3]
If I try to run services ("sh service start")
I obtain as a result the MAN specifications on how to use the docker-compose command and, I think it means that we are wrongly trying to use it!

Maybe you can solve it by removing the option `--log-level ERROR`

**Comment by jason-fox** [comment]
@tmontanaro please check the version of `docker-compose` you are using. According to the [release notes](https://docs.docker.com/release-notes/docker-compose/#1200) the `--log-level` command has been supported since version `1.20.0`

The recommended minimum version according to the [tutorial documentation](https://fiware-tutorials.readthedocs.io/en/latest/#prerequisites) is version `1.21`.

Ideally I don't want to remove the `--log-level` command just to offer support for legacy versions of `docker-compose`

**Comment by tmontanaro** [comment]
Ok, my fault:
I installed it through the apt tool in Ubuntu 18.04 and the last version is 1.17.1-2.
So, (for other users having the same issue) to fix the bug it is enough to update docker-compose to the last version ([Source](https://docs.docker.com/compose/install/)):
 - ```sudo curl -L https://github.com/docker/compose/releases/download/1.24.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose```
- ```sudo chmod +x /usr/local/bin/docker-compose```
